### ISSUE TITLE
water temperature for tiefenbrunnen is broken

### ISSUE THREAD

**Issue by eydrian** [metaodi/tecdottir#11]
it returns 

```json
"Wassertemp. (DEFEKT)": {
          "value": "14.8",
          "unit": "°C"
        },
```

**Comment by eydrian** [comment]
it seams like the endpoint https://www.tecson-data.ch/zurich/tiefenbrunner/uebersicht/messwerte.php is not responding correct data

**Comment by eydrian** [comment]
it's a problem with https://www.tecson-data.ch/zurich/tiefenbrunnen/uebersicht/messwerte.php nothing to do with this. Closing

**Comment by metaodi** [comment]
Yes this has been reported in #10 as well.

I don't really know if the API should be adapted or not.

**Comment by eydrian** [comment]
wow you’re fast, let me know if I can be of assistance. 
I appreciate the app very much

**Comment by metaodi** [comment]
What do you think? I could map "Wassertemp. (DEFEKT)" to `water_temperature` like it was before. And maybe add an indication, that the value is broken. Something like that:

```
"water_temperature": {
          "value": "14.8",
          "unit": "°C",
          "status": "broken"
        },
```

But since I don't know what exectly is broken, I'm a bit hesitant.

**Comment by eydrian** [comment]
I think at least that would not break a consumer. Problem here is, that the API is not consistent anymore.

**Comment by 01241** [comment]
If you have time to change it, for me this solution is perfect. Link for the section "Showcases"   :)
[https://editioneffet.ch/03069/zuerichhorn.html](url)
Thanks metadodi

**Comment by metaodi** [comment]
@01241 thanks a lot, added you to the README.

I'm working on this in #12 (nearly ready to merge), it will add an additional `status` field to all measurements and indicate either `ok` or `broken`. `broken` means that in the original label the word "DEFEKT" is found.

I currently have no idea what this exactly means, but I thinks it's a good idea to expose this to a consumer.

**Comment by metaodi** [comment]
tecdottir 0.0.2 with these changes is now deployed at http://tecdottir.herokuapp.com/
