### ISSUE TITLE
API request error: Unauthorized

### ISSUE THREAD

**Issue by NickSB** [metaodi/tecdottir#25]
Recently, the API query no longer works. The following error message appears: 

{"ok":false,"message":"Tecson returned an error: Error: Unauthorized"}

The following query was performed: 
https://tecdottir.herokuapp.com/measurements/tiefenbrunnen?startDate=2022-01-06&endDate=2022-01-06

Do I have to log in or submit a token now?

It also no longer works on the API reference page: 
https://tecdottir.herokuapp.com/docs/

**Comment by metaodi** [comment]
Unfortunately Tecson, the provider of the data, added an authentication to their service without notice.

But the data is now being updated every ~30min as a CSV here: https://data.stadt-zuerich.ch/dataset/sid_wapo_wetterstationen#dataset

So I think I will switch to this data source and base the API on this CSVs instead.

**Comment by metaodi** [comment]
I just released Tecdottir 1.0.0, the API is working again.
