### ISSUE TITLE
Data Refresh

### ISSUE THREAD

**Issue by PeterGian** [metaodi/tecdottir#41]
Hello, first of all, thanks for your work!
Secondly, I wanted to ask if it is possible to increase the number of updates during the day.
I'm trying to create an "Alexa" skill to retrieve the temperature but as far as I can see the data is rather old.
For example, I'm performing a query at 16:09 and the result is "value": "2023-02-02T13:30:00+01:00".
Let me already say thank you if you would have the chance to work on this suggestion!

**Comment by metaodi** [comment]
This is a bit tricky: I actually update the data every 15min, but the [source](https://data.stadt-zuerich.ch/dataset/sid_wapo_wetterstationen) is currently only updated every 3 hours. But let me check with Open Data Zurich if it's possible to increase the frequency.

**Comment by metaodi** [comment]
The data at the source is now updated every 90min, so you should get more up to date data now.

**Comment by PeterGian** [comment]
Thanks Stefan! Really appreciated.

Il sab 18 feb 2023, 08:07 Stefan Oderbolz ***@***.***> ha
scritto:
