### ISSUE TITLE
Recent data is empty for the current month

### ISSUE THREAD

**Issue by eydrian** [metaodi/tecdottir#42]
Hey I have a question

I was running this command successfully since a very long time. But since approx a year, the current month is always empty:

```
curl -X 'GET' 'https://tecdottir.herokuapp.com/measurements/tiefenbrunnen?startDate=2023-03-13&endDate=2023-03-14&sort=timestamp_cet%20desc&offset=0' -H "accept: application/json"

```

```
{"ok":true,"total_count":0,"row_count":0,"result":[]}%
```

Any idea what I'm doing wrong?

**Comment by metaodi** [comment]
@eydrian Unfortunately the data provider stopped providing data. I'm not really sure how to continue this project, but hopefully there will be data again, maybe from another source.

**Comment by metaodi** [comment]
Small update: I'm starting to collect data again, so hopefully current data should be available again.

**Comment by metaodi** [comment]
The data provider switched to a more reliable way of providing its data, we once again receive better data in ~20min intervals. Lookshgood so far
