### ISSUE TITLE
Enable TLS 1.3

### ISSUE THREAD

**Issue by robertbastian** [metaodi/tecdottir#47]
I'm trying to use the API from a system that doesn't support TLS 1.2. However, at the moment the API [only supports TLS 1.2](https://www.cdn77.com/tls-test/result?domain=tecdottir.herokuapp.com). [Heroku says it supports TLS 1.2 and 1.3](https://devcenter.heroku.com/articles/ssl#supported-ssl-protocols), so maybe there's a button somewhere that you could click to enable 1.3? Thanks!

**Comment by metaodi** [comment]
@robertbastian I'm not sure I'm able to fix this. I don't know which option I need to enable. I probably need to use a custom domain name (?)

If anyone knows how to enable this on a standard heroku instance, please let me know.

**Comment by robertbastian** [comment]
Maybe the "Upgrade stack" button does something? Which stack are you using?
 
<img width="452" alt="image" src="https://github.com/user-attachments/assets/769ec586-a782-439f-aaf2-b055e8b9965e">

**Comment by robertbastian** [comment]
It looks like TLS 1.3 was added to the heroku-18 stack in 2019: https://devcenter.heroku.com/changelog-items/1681. Presumably older stacks don't support it.

**Comment by metaodi** [comment]
I just recently upgraded to heroku-24 🤷‍♂️

**Comment by robertbastian** [comment]
I could reproduce this, and confirmed that adding a custom domain enables TLS 1.3. It looks like the herokuapp.com domain just doesn't support it :(

**Comment by metaodi** [comment]
I'll probably soon move this application to a custom domain and switch the hosting from Heroku to fly.io.

**Comment by metaodi** [comment]
Now tecdottir is available at https://tecdottir.metaodi.ch and supports TLS 1.3 :smile:
